### ISSUE TITLE
Public URL for schemaLocation

### ISSUE THREAD

**Issue by hectcastro** [usnistgov/Voting#1]
Outside of a [raw URL](https://raw.githubusercontent.com/usnistgov/Voting/master/NIST_V1_election_resultsV50.xsd) GitHub provides, is there a definitive public URL that can be used within the `schema` element for an XML file that intends to adhere to the NIST common election data format?

**Comment by johnpwack** [comment]
Apologies for the lengthy amount of time it's taken me to reply.  Currently, we don't have a definitive URL other than GitHub.  I'll look into establishing one and get back to you.

**Comment by JDziurlaj** [comment]
See #10. We will use URIs, however, they do not resolve as URLs.
